# =============================================================================
# Fly.io Configuration for RAG Sustainability Chatbot (High Memory)
# =============================================================================
# This configuration uses more memory to handle the large vector store
# during startup and operation.
# =============================================================================

# Application name - should match your existing app
app = "sustainability-bot-with-3d-plot"

# Fly.io platform version
version = 2

# Build configuration
[build]
  # Use the Dockerfile in the current directory
  dockerfile = "Dockerfile"

# Environment variables (non-secret)
[env]
  # Tell the app it's running in Docker/production mode
  DOCKER_ENV = "true"
  # Python optimization
  PYTHONUNBUFFERED = "1"

# HTTP service configuration
[[services]]
  # Internal port (what the app listens on inside the container)
  internal_port = 7860
  
  # Protocol for the service
  protocol = "tcp"
  
  # Simplified auto-scaling for high memory
  auto_start_machines = true
  min_machines_running = 1
  max_machines_running = 1  # Keep to 1 machine for cost control

  # Extended health checks for ML app startup
  [[services.tcp_checks]]
    grace_period = "300s"    # 5 minutes grace period for vector store loading
    interval = "60s"         # Check every minute
    restart_limit = 2        # Fewer restarts to avoid restart loops
    timeout = "45s"          # Longer timeout for health checks

  # Port configuration for external access
  [[services.ports]]
    force_https = true       # Always redirect HTTP to HTTPS
    handlers = ["http"]      # Handle HTTP requests
    port = 80               # External port for HTTP (redirects to HTTPS)

  [[services.ports]]
    handlers = ["tls", "http"]  # Handle HTTPS requests
    port = 443                  # External port for HTTPS

# Resource allocation - Use more memory for vector store
[vm]
  # Upgrade to dedicated CPU with more memory
  size = "dedicated-cpu-1x"   # 1 dedicated vCPU, 2GB RAM base
  memory = "8gb"              # 8GB total memory for vector store + operations

# Region configuration
[placement]
  # Primary region for deployment
  region = "lhr"             # London Heathrow

# =============================================================================
# Usage Instructions:
#
# 1. This configuration uses 8GB memory to handle:
#    - 500MB vector store
#    - Python dependencies and ML libraries
#    - PCA computation on embeddings
#    - Gradio interface and runtime overhead
#
# 2. To use this configuration:
#    cp fly-high-memory.toml fly.toml
#    flyctl deploy
#
# 3. Cost: ~$30-50/month for dedicated-cpu-1x with 8GB
#    (vs ~$15-20/month for shared-cpu-2x with 4GB)
#
# 4. Monitor memory usage after deployment:
#    flyctl status
#    flyctl logs
# ============================================================================= 