# =============================================================================
# Fly.io Configuration for RAG Sustainability Chatbot (No Health Checks)
# =============================================================================
# This is a simplified version for initial deployment without health checks
# to help debug connection issues.
# =============================================================================

# Application name - CHANGE THIS to something unique for your deployment
app = "sustainability-bot-with-3d-plot"

# Fly.io platform version
version = 2

# Build configuration
[build]
  # Use the Dockerfile in the current directory
  dockerfile = "Dockerfile"

# Environment variables (non-secret)
[env]
  # Tell the app it's running in Docker/production mode
  DOCKER_ENV = "true"
  # Python optimization
  PYTHONUNBUFFERED = "1"

# HTTP service configuration
[[services]]
  # Internal port (what the app listens on inside the container)
  internal_port = 7860
  
  # Protocol for the service
  protocol = "tcp"
  
  # Simplified auto-scaling
  auto_start_machines = true
  min_machines_running = 1
  
  # NO HEALTH CHECKS for initial deployment
  # This removes the timeout issues while we debug

  # Port configuration for external access
  [[services.ports]]
    force_https = true       # Always redirect HTTP to HTTPS
    handlers = ["http"]      # Handle HTTP requests
    port = 80               # External port for HTTP (redirects to HTTPS)

  [[services.ports]]
    handlers = ["tls", "http"]  # Handle HTTPS requests
    port = 443                  # External port for HTTPS

# Resource allocation - Balanced for ML workload responsiveness
[vm]
  # Virtual machine configuration (correct syntax for Fly.io v2)
  size = "shared-cpu-2x"    # 2 vCPU needed for ML operations and responsiveness
  
  # Memory allocation - optimized but sufficient
  memory = "2gb"            # Reduced from 4GB but provides processing headroom

# Region configuration
[placement]
  # Primary region for deployment
  region = "lhr"             # London Heathrow

# =============================================================================
# Deployment Instructions for Debugging:
#
# 1. Copy this file over fly.toml:
#    cp fly-no-healthcheck.toml fly.toml
#
# 2. Deploy without health checks:
#    flyctl deploy
#
# 3. Check if the app starts properly:
#    flyctl logs
#
# 4. Test the endpoint:
#    flyctl open
#
# 5. Once working, add health checks back gradually
# ============================================================================= 